### ISSUE TITLE
Invalid folder structure for pages with slash /

### ISSUE THREAD

**Issue by tmotyl** [gergelykalman/confluence-markdown-exporter#10]
If a page in confluence contains a "/" e.g. "Page for (Sales/Marketing)" the tool will create following directory structure:
```
Space 
  -> Page for (Sales
   ->-> Marketing)
```
Where "Marketing)" folder is a subfolder of "Page for (Sales"

probably missing sanitization around https://github.com/gergelykalman/confluence-markdown-exporter/blob/main/confluence-markdown-export.py#L97 
should be:
```
self.__dump_page(child_id, parents=parents + [ self.__sanitize_filename(page_title)])
```

**Comment by gergelykalman** [comment]
This is not happening on the latest HEAD. Before reporting a bug please make sure it happens with the latest in main.

**Comment by tmotyl** [comment]
@gergelykalman have you tested this case?
I tested it using this commit eece3b0baf6aa79c088607cf4eb6a74773c9b389 which is a HEAD of the current `main` branch.
Or maybe you have some local commits which are not pushed to the repo?

**Comment by gergelykalman** [comment]
I found it, this only happens if pages exist who are children of pages with slashes in the title. A sanitization check was missing from the parents' path segment, so this is a security issue. I fixed it in an issue branch, I'll merge the commit.

Thanks!
