### ISSUE TITLE
On missing attachments (404s) in Confluence, log the error instead of terminating

### ISSUE THREAD

**Issue by gergelykalman** [gergelykalman/confluence-markdown-exporter#12]
Reported in https://github.com/gergelykalman/confluence-markdown-exporter/pull/9

**Comment by tmotyl** [comment]
similar issue is when given space has no parent page. The script stops instead of continuing.

**Comment by gergelykalman** [comment]
@tmotyl Can you give me an example for this or a way to reproduce?

**Comment by gergelykalman** [comment]
Fixed in 3506ce2a697bfea97a7423dfd1442bf504c9885e

Let me know about the no parent issue

**Comment by tmotyl** [comment]
The script to work expects every space to have a single page which is a root page for the space - all pages have to be it descendants. But its possible to have space in confluence which has few pages on the root level or to have no page configured as a “home” for given space
