### ISSUE TITLE
Super slow attachment downloads

### ISSUE THREAD

**Issue by spyhunter99** [gergelykalman/confluence-markdown-exporter#23]
I'm on SSD with just confluence, postgres and this tool all on localhost. Download speeds are at like 150KB/s. Large attachments take hours to download. Is there anything you can suggest? I tried adding user agents, increasing tomcat's connection timeouts and ensuring that rate limiting is disabled. I'm not sure what the bottle neck is

**Comment by gergelykalman** [comment]
Hmm. This is https://pypi.org/project/atlassian-python-api/ that I use to do the actual heavy lifting.

You might try a fresher version of that package, maybe it was a bug they fixed.

I will release a version with updated requirements later today. Let me know if the issue persists and I'll see into this further.

**Comment by gergelykalman** [comment]
Fixed in 4502bfe54f4891943b09b2f4950819e9637c0e3d
